compression module: mc_compact() - Added flag `n`
OpenSIPS/opensips pull request #2703
Opened 2021-11-28 12:48 UTC by ar45

**Summary**
compression module: mc_compact() - Added flag `n`

**Details**
FEATURE

Added flags param which accepts `n` for no compact headers.
    When specified, opensips will only remove headers not in the whitelist
    without using the compact form for From/To/CallID etc.
    `mc_compact( ... , "n")`

**Solution**
The motive for this is, because some UAs do not understand the compact form
    I've also encountered weird bugs using the compact form with some UAs.

**Compatibility**
The flags param is optional and defaults to the old behavior to using compact header names.

2022-01-05 08:57 UTC, bogdan-iancu commented on modules/compression/compression.c
> +	flags = pkg_malloc(sizeof *flags);
There is no need to allocate here the int for the flags, you can store the value directly over the `void *` (its size is larger or the same as of an `int`). Check how is done here https://github.com/OpenSIPS/opensips/blob/master/modules/drouting/drouting.c#L3870

2022-03-08 06:58 UTC, ar45 commented
Still waiting

2022-04-08 07:44 UTC, bogdan-iancu commented on modules/compression/compression.c
> +		{CMD_PARAM_STR|CMD_PARAM_OPT|CMD_PARAM_FIX_NULL,
Please add the details on this new `n` flag into the documentation file ( modules/compression/doc/compression_admin.xml ).

2022-04-08 07:45 UTC, bogdan-iancu requested changes
Just update the README

2022-04-12 06:46 UTC, bogdan-iancu commented
@ar45 , as per my request, you need to update the `modules/compression/doc/compression_admin.xml ` file (switch is not part of your PR here). There is no need to commit changes on the actual README file as this one is auto-generated based on the xml one.

2022-04-13 06:19 UTC, bogdan-iancu approved these changes

2022-04-13 06:21 UTC, bogdan-iancu commented
All good @ar45 , thanks for the work and patience here. I was about to merge your PR when I realized that it is against 3.2 branch, not against master . The 3.2 is a stable release, not accepting new features, only fixes. New features go only into master - so please re-do this PR against the masters (and close this one)

2022-04-13 06:58 UTC, ar45 commented
@bogdan-iancu Thank you and sorry for that. I updated the PR to be against master.

2022-04-15 11:22 UTC, merged